### ISSUE TITLE
Insufficient URL encoding

### ISSUE THREAD

**Issue by stefanb** [jeancaffou/upn-qr#5]
When URL is copied from the browser's address bar the parameter is not fully URL encoded:

Eg:
`https://jeancaffou.github.io/upn-qr/?upn={%22prejemnik%22:%22Name%22,%22name%22:null,%22naslov%22:null,%22prnaslov%22:null,%22posta%22:null,%22prposta%22:null,%22date%22:null,%22trr%22:null,%22ref%22:%22SI99%22,%22znesek%22:0,%22koda%22:%22GDSV%22,%22namen%22:null}`

Notice the non-url-encoded `{` at the beginning and `}` at the end of `upn` query string parameter.

Twitter thinks the URL ends at `{`, losing the URL parameter value:
<img width="335" alt="image" src="https://github.com/jeancaffou/upn-qr/assets/319826/91b5c772-9d0f-40af-a4a7-ad6666c89e39">

Url escaping these two characters fixes the problem:
<img width="297" alt="image" src="https://github.com/jeancaffou/upn-qr/assets/319826/6d5868e1-9eb6-4f73-8503-9c8cb7c0bd3d">

Not sure if it is a problem in this app or the browsers (both Chrome and Firefox behave the same), but it could likely be worked around in the app (either forcing URL encoding or in worst case adding a "share" button which would copy the proper URL to the clipboard).

**Comment by jeancaffou** [comment]
@stefanb is the same issue now with the hash params?

**Comment by stefanb** [comment]
No, after fixing #4 the url copied to the clipboard became `https://jeancaffou.github.io/upn-qr/#/?upn={%22prejemnik%22:null,%22name%22:%22TEST%22,%22naslov%22:null,%22prnaslov%22:null,%22posta%22:null,%22prposta%22:null,%22date%22:null,%22trr%22:null,%22ref%22:%22SI99%22,%22znesek%22:0,%22koda%22:%22GDSV%22,%22namen%22:null}`

Still leaving `{` and `}` non-url-encoded

**Comment by stefanb** [comment]
Some characters in the copied URL are now URL-encoded twice, making the URL longer than necesarry:
https://jeancaffou.github.io/upn-qr/#/?upn=%257B%2522prejemnik%2522%253A%2522TEST%2522%252C%2522name%2522%253Anull%252C%2522naslov%2522%253Anull%252C%2522prnaslov%2522%253Anull%252C%2522posta%2522%253Anull%252C%2522prposta%2522%253Anull%252C%2522date%2522%253Anull%252C%2522trr%2522%253Anull%252C%2522ref%2522%253A%2522SI99%2522%252C%2522znesek%2522%253A0%252C%2522koda%2522%253A%2522GDSV%2522%252C%2522namen%2522%253Anull%257D

But it works :)

**Comment by stefanb** [comment]
Thanks for both fixes!
